# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data
# in a particular coordinate frame.

# Two-integer timestamp that is expressed as seconds and nanoseconds.
builtin_interfaces/Time stamp
int64 data8
int64 data16
int64 data32
int64 data40
int64 data56
int64 data48
int64 data64


# Transform frame with which this data is associated.
string frame_id
